### ISSUE TITLE
 values related to parameters of S-MAC

### ISSUE THREAD

**Issue by pakizeh** [boulis/Castalia#18]
hi
can anyone help me?
1-I need to have the values of some of the s-mac protocol parameters that used in Castalia. As  DIFS duration, Contention Window size, size of SlotTime, backoff time ,SYNC duration( duration of a sync cycle = 6 ms? )
I would be very grateful if anyone gave me these values .
2-  Is the CBR value obtained through "Application.packet_rate *Application.constantDataPayload" ?
3- What is the unit of Consumed Energy in the ResourceManager module? mW of nJ or ...?
I would truly appreciate your advice on this.

**Comment by boulis** [comment]
Github issues should be more about the bugs and features in the code, not general help about Castalia. Use stackoverflow to ask your question making sure you include the word Castalia in the title. For example: "Castalia S-MAC parameters" You can also add the tag omnet++

**Comment by pakizeh** [comment]
Thank you

**Comment by pakizeh** [comment]
Dear Boulis,
I want to model and evaluate the S-MAC Protocol with Petri Net. Then
compare the results with the results from Castalia. Could you give me some
suggestions for this modeling,please.
can you help me?
I ask my question in stackoverflow but i am in a hurry for it.
1-To do this, I need to have the values of some of the protocol parameters
that you used in Castalia. As  DIFS duration, Contention Window size, size
of SlotTime, backoff time ,SYNC duration( duration of a sync cycle = 6 ms? )
I would be very grateful if you gave me these values or the names of the
variables that are related to these parameters.
2-  Is the CBR value obtained through "Application.packet_rate
*Application.constantDataPayload" ?
3- What is the unit of Consumed Energy in the ResourceManager module? mW of
nJ or ...?
4-Is "SN.numNodes" number of nodes in a virtual cluster? if not, what
calculate number of nodes in a virtual cluste?

I read User’s Manual of castalia, but still couldn't find the answers to my
questions
I would truly appreciate your advice on this.

Best regards,
Pakizeh
